### ISSUE TITLE
Crashes upon opening

### ISSUE THREAD

**Issue by Axiulze** [JustEmuTarkov/JET-ProfileEditor#4]

**Comment by ProjektCode** [comment]
Mine crashes when I select my jet server directory. and then after that, it won't open at all. are you having this issue as well?

**Comment by Axiulze** [comment]
Yep.

**Comment by themaoci** [comment]
propably wrong file structure in server or something similar

**Comment by whirly10** [comment]
hi is there any solution to the crash? im having same issue. thanks

**Comment by Jeddunk** [comment]
Profile editor crashes if the server is running. **After shutting down the server I'm able to use the editor.**

The crash happens because the profile editor is a 32-bit application that is trying to access a 64-bit application (server.exe).

![image](https://user-images.githubusercontent.com/2891973/115414565-6f85d280-a1f6-11eb-8158-47c9dfff9519.png)

**Comment by kura1337** [comment]
did you fix it ?

**Comment by Jeddunk** [comment]
> did you fix it ?

Read my previous comment.

**Comment by eddielane71488** [comment]
This crash is resolved by adding the directory to the exclusion list for your anti-virus
